server:
  http_listen_port: 9080
  log_level: info

clients:
  - url: http://13.48.137.44:3100/loki/api/v1/push

# 1. Collect from systemd journal (employee-api.service)
scrape_configs:
  - job_name: systemd-journal
    journal:
      max_age: 12h
      labels:
        job: employee-api
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: 'employee-api\.service'
        action: keep

# 2. Collect from log files (e.g., /var/log/employee-api.log)
  - job_name: employee-api-file-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: employee-api
          __path__: /var/log/employee-api.log
