- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart postgres_exporter
  ansible.builtin.systemd:
    name: postgres_exporter
    state: restarted
    enabled: yes
